--@Autor:          Gustavo Santana Sánchez, Rodrigo García Peñafort
--@Fecha creación: 06/06/2026 1:54 a.m.
--@Descripción:    Creación de fragmentos en el sitio Este (GSS_S2)



CREATE TABLE HISTORICO_STATUS_LAPTOP_F1_GSS_S2(
    HISTORICO_STATUS_LAPTOP_ID    NUMBER(10, 0)    NOT NULL,
    LAPTOP_ID                     NUMBER(10, 0)    NOT NULL,
    FECHA_STATUS                  DATE     		   NOT NULL,
    STATUS_LAPTOP_ID              NUMBER(5, 0)     NOT NULL,
    CONSTRAINT HISTORICO_F1_PK PRIMARY KEY (HISTORICO_STATUS_LAPTOP_ID)
);


CREATE TABLE LAPTOP_F3_GSS_S2(
    LAPTOP_ID                 NUMBER(10, 0)     NOT NULL,
    LAPTOP_REEMPLAZO_ID       NUMBER(10, 0),
    NUM_SERIE                 VARCHAR2(18)      NOT NULL,
    CANTIDAD_RAM              NUMBER(6, 0)      NOT NULL,
    CARACTERISTICAS_EXTRAS    VARCHAR2(2000)    NOT NULL,
    TIPO_PROCESADOR_ID        NUMBER(5, 0)      NOT NULL,
    TIPO_TARJETA_VIDEO_ID     NUMBER(5, 0)      NOT NULL,
    TIPO_ALMACENAMIENTO_ID    NUMBER(5, 0)      NOT NULL,
    TIPO_MONITOR_ID           NUMBER(5, 0)      NOT NULL,
    CONSTRAINT LAPTOP_F3_PK PRIMARY KEY (LAPTOP_ID)
);


CREATE TABLE SERVICIO_LAPTOP_F2_GSS_S2(
    NUM_SERVICIO    NUMBER(10, 0)     NOT NULL,
    LAPTOP_ID       NUMBER(10, 0)     NOT NULL,
    IMPORTE         NUMBER(8, 2)      NOT NULL,
    DIAGNOSTICO     VARCHAR2(2000)    NOT NULL,
    FACTURA         BLOB              NOT NULL,
    SUCURSAL_ID     NUMBER(10, 0)     NOT NULL,
    CONSTRAINT SERVICIO_LAPTOP_F2_PK PRIMARY KEY (NUM_SERVICIO, LAPTOP_ID)
);


CREATE TABLE STATUS_LAPTOP(
    STATUS_LAPTOP_ID    NUMBER(5, 0)     NOT NULL,
    CLAVE               VARCHAR2(40)     NOT NULL,
    DESCRIPCION         VARCHAR2(400)    NOT NULL,
    CONSTRAINT STATUS_LAPTOP_PK PRIMARY KEY (STATUS_LAPTOP_ID)
);


CREATE TABLE SUCURSAL_F2_GSS_S2(
    SUCURSAL_ID    NUMBER(10, 0)    NOT NULL,
    CLAVE          VARCHAR2(10)     NOT NULL,
    ES_TALLER      NUMBER(1, 0)     NOT NULL,
    ES_VENTA       NUMBER(1, 0)     NOT NULL,
    NOMBRE         VARCHAR2(40)     NOT NULL,
    LATITUD        BINARY_FLOAT     NOT NULL,
    LONGITUD       BINARY_FLOAT     NOT NULL,
    URL            VARCHAR2(200)    NOT NULL,
    CONSTRAINT SUCURSAL_F2_PK PRIMARY KEY (SUCURSAL_ID)
);


CREATE TABLE SUCURSAL_TALLER_F2_GSS_S2(
    SUCURSAL_ID          NUMBER(10, 0)    NOT NULL,
    DIA_DESCANSO         NUMBER(1, 0)     NOT NULL,
    TELEFONO_ATENCION    VARCHAR2(20)     NOT NULL,
    CONSTRAINT SUCURSAL_TALLER_F2_PK PRIMARY KEY (SUCURSAL_ID)
);


CREATE TABLE SUCURSAL_VENTA_F2_GSS_S2(
    SUCURSAL_ID      NUMBER(10, 0)    NOT NULL,
    HORA_APERTURA    DATE             NOT NULL,
    HORA_CIERRE      DATE             NOT NULL,
    CONSTRAINT SUCURSAL_VENTA_F2_PK PRIMARY KEY (SUCURSAL_ID)
);


CREATE TABLE TIPO_ALMACENAMIENTO_R_GSS_S2(
    TIPO_ALMACENAMIENTO_ID    NUMBER(5, 0)     NOT NULL,
    CLAVE                     VARCHAR2(40)     NOT NULL,
    DESCRIPCION               VARCHAR2(400)    NOT NULL,
    CONSTRAINT TIPO_ALMACENAMIENTO_GSS_S2_PK PRIMARY KEY (TIPO_ALMACENAMIENTO_ID)
);


CREATE TABLE TIPO_MONITOR_R_GSS_S2(
    TIPO_MONITOR_ID    NUMBER(5, 0)     NOT NULL,
    CLAVE              VARCHAR2(40)     NOT NULL,
    DESCRIPCION        VARCHAR2(400)    NOT NULL,
    CONSTRAINT TIPO_MONITOR_GSS_S2_PK PRIMARY KEY (TIPO_MONITOR_ID)
);


CREATE TABLE TIPO_PROCESADOR_R_GSS_S2(
    TIPO_PROCESADOR_ID    NUMBER(5, 0)     NOT NULL,
    CLAVE                 VARCHAR2(40)     NOT NULL,
    DESCRIPCION           VARCHAR2(400)    NOT NULL,
    CONSTRAINT TIPO_PROCESADOR_GSS_S2_PK PRIMARY KEY (TIPO_PROCESADOR_ID)
);


CREATE TABLE TIPO_TARJETA_VIDEO_R_GSS_S2(
    TIPO_TARJETA_VIDEO_ID    NUMBER(5, 0)     NOT NULL,
    CLAVE                    VARCHAR2(40)     NOT NULL,
    DESCRIPCION              VARCHAR2(400)    NOT NULL,
    CONSTRAINT TIPO_TARJETA_GSS_S2_PK PRIMARY KEY (TIPO_TARJETA_VIDEO_ID)
);



--
-- TABLE: HISTORICO_STATUS_LAPTOP_F1_GSS_S2
--

ALTER TABLE HISTORICO_STATUS_LAPTOP_F1_GSS_S2 ADD CONSTRAINT HIST_ST_LAP_F1_STATUS_LAP_ID_fk
    FOREIGN KEY (STATUS_LAPTOP_ID)
    REFERENCES STATUS_LAPTOP(STATUS_LAPTOP_ID);


--
-- TABLE: LAPTOP_F3_GSS_S2
--

ALTER TABLE LAPTOP_F3_GSS_S2 ADD CONSTRAINT LAP_F3_TIPO_PROC_ID_fk
    FOREIGN KEY (TIPO_PROCESADOR_ID)
    REFERENCES TIPO_PROCESADOR_R_GSS_S2(TIPO_PROCESADOR_ID);

ALTER TABLE LAPTOP_F3_GSS_S2 ADD CONSTRAINT LAP_F3_TIPO_TARJ_VID_ID_fk
    FOREIGN KEY (TIPO_TARJETA_VIDEO_ID)
    REFERENCES TIPO_TARJETA_VIDEO_R_GSS_S2(TIPO_TARJETA_VIDEO_ID);

ALTER TABLE LAPTOP_F3_GSS_S2 ADD CONSTRAINT LAP_F3_TIPO_ALM_ID_fk
    FOREIGN KEY (TIPO_ALMACENAMIENTO_ID)
    REFERENCES TIPO_ALMACENAMIENTO_R_GSS_S2(TIPO_ALMACENAMIENTO_ID);

ALTER TABLE LAPTOP_F3_GSS_S2 ADD CONSTRAINT LAP_F3_TIPO_MON_ID_fk
    FOREIGN KEY (TIPO_MONITOR_ID)
    REFERENCES TIPO_MONITOR_R_GSS_S2(TIPO_MONITOR_ID);


--
-- TABLE: SERVICIO_LAPTOP_F2_GSS_S2
--

ALTER TABLE SERVICIO_LAPTOP_F2_GSS_S2 ADD CONSTRAINT SERV_LAP_F2_SUCURSAL_ID_fk
    FOREIGN KEY (SUCURSAL_ID)
    REFERENCES SUCURSAL_TALLER_F2_GSS_S2(SUCURSAL_ID);


--
-- TABLE: SUCURSAL_TALLER_F2_GSS_S2
--

ALTER TABLE SUCURSAL_TALLER_F2_GSS_S2 ADD CONSTRAINT SUC_TALL_F2_SUCURSAL_ID_fk
    FOREIGN KEY (SUCURSAL_ID)
    REFERENCES SUCURSAL_F2_GSS_S2(SUCURSAL_ID);


--
-- TABLE: SUCURSAL_VENTA_F2_GSS_S2
--

ALTER TABLE SUCURSAL_VENTA_F2_GSS_S2 ADD CONSTRAINT SUC_VTA_F2_SUCURSAL_ID_fk
    FOREIGN KEY (SUCURSAL_ID)
    REFERENCES SUCURSAL_F2_GSS_S2(SUCURSAL_ID);





